"""Response chain — what user submitted, AI evaluation, AI feedback."""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, JSON, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.core.mixins import CreatedAtMixin, IDMixin


# UserResponse — what the user submitted
class UserResponse(Base, IDMixin, CreatedAtMixin):
    """
    A user's submission for an assigned task.

    `content` shape varies by task_type:
      - fill-in-blanks: {"Q1": "answer", "Q2": ...}
      - writing: {"text": "..."}
      - speaking (later): {"audio_url": "...", "transcript": "..."}
    """

    __tablename__ = "user_responses"

    user_task_id: Mapped[int] = mapped_column(
        ForeignKey("user_tasks.id", ondelete="CASCADE"),
        nullable=False, unique=True, index=True,
    )
    content: Mapped[dict] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
    )
    raw_text: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Embedding state — async side-effect, doesn't block submission
    embedding_status: Mapped[str] = mapped_column(
        Text, nullable=False, server_default="pending", index=True,
    )
    pinecone_vector_id: Mapped[str | None] = mapped_column(
        Text, nullable=True,
    )
    
    # Relationships 
    evaluation: Mapped["Evaluation | None"] = relationship(
        back_populates="response",
        cascade="all, delete-orphan",
        uselist=False,
    )

    def __repr__(self) -> str:
        return f"<UserResponse(id={self.id}, user_task_id={self.user_task_id})>"


# Evaluation — Agent 2 output (structured machine-readable scoring)
class Evaluation(Base, IDMixin, CreatedAtMixin):
    """
    Structured evaluation report from the Evaluation Agent.

    `report` is the full JSON: per-question correctness, error types,
    section scores, error patterns. This is the SOURCE OF TRUTH.

    Feedback can be regenerated from this without re-evaluating.
    """

    __tablename__ = "evaluations"

    response_id: Mapped[int] = mapped_column(
        ForeignKey("user_responses.id", ondelete="CASCADE"),
        nullable=False, unique=True, index=True,
    )
    overall_score: Mapped[float] = mapped_column(Numeric(4, 2), nullable=False)
    percentage: Mapped[float] = mapped_column(Numeric(5, 2), nullable=False)
    report: Mapped[dict] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
    )

    # Relationships
    response: Mapped["UserResponse"] = relationship(back_populates="evaluation")
    feedback: Mapped["Feedback | None"] = relationship(
        back_populates="evaluation",
        cascade="all, delete-orphan",
        uselist=False,
    )

    def __repr__(self) -> str:
        return (
            f"<Evaluation(id={self.id}, response_id={self.response_id}, "
            f"score={self.overall_score})>"
        )


# Feedback — Agent 3 output (human-readable corrective feedback)
class Feedback(Base, IDMixin, CreatedAtMixin):
    """
    Human-readable feedback generated by the Feedback Agent.

    `body` is the structured feedback JSON: overall message, detailed
    per-error explanations, practice suggestion, pattern warning.

    Multiple feedbacks can theoretically come from one evaluation
    (different tones, regenerated with better model). MVP: one-to-one.
    """

    __tablename__ = "feedbacks"

    evaluation_id: Mapped[int] = mapped_column(
        ForeignKey("evaluations.id", ondelete="CASCADE"),
        nullable=False, unique=True, index=True,
    )
    body: Mapped[dict] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
    )
    review_status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="pending",
        server_default="pending",
        index=True,
    )
    reviewed_by: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    reviewed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )
    admin_note: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Relationships
    evaluation: Mapped["Evaluation"] = relationship(back_populates="feedback")
    reviewer = relationship("User")

    def __repr__(self) -> str:
        return f"<Feedback(id={self.id}, evaluation_id={self.evaluation_id})>"
