"""squashed_initial_schema

Revision ID: 17e15923f549
Revises:
Create Date: 2026-05-14 09:06:16.783212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "17e15923f549"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("duration_weeks", sa.Integer(), nullable=False),
        sa.Column(
            "target_level",
            sa.Enum("beginner", "intermediate", "advanced", name="course_level_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="course_status_enum"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    op.create_index(op.f("ix_courses_status"), "courses", ["status"], unique=False)
    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "reading",
                "writing",
                "speaking",
                "listening",
                "fill_in_blanks",
                "error_spotting",
                "sentence_transformation",
                "voice_conversion",
                "error_correction",
                "speak_with_tense",
                "curriculum_grammar_fill_blanks",
                "curriculum_grammar_open_text",
                "curriculum_grammar_listen_mcq",
                "curriculum_grammar_speak",
                "curriculum_vocab_mcq",
                "curriculum_vocab_open_text",
                "curriculum_vocab_listen_mcq",
                "curriculum_vocab_speak",
                "curriculum_pron_read_aloud",
                "curriculum_pron_phonetic_mcq",
                "curriculum_pron_listen_discriminate",
                "curriculum_pron_speak_drill",
                "curriculum_fluency_speed_read",
                "curriculum_fluency_timed_write",
                "curriculum_fluency_shadow",
                "curriculum_fluency_speak",
                "curriculum_expression_summarize",
                "curriculum_expression_essay",
                "curriculum_expression_listen_structure",
                "curriculum_expression_storyboard",
                "curriculum_comprehension_read_mcq",
                "curriculum_comprehension_write_answers",
                "curriculum_comprehension_listen_mcq",
                "curriculum_comprehension_retell",
                "curriculum_tone_read_mcq",
                "curriculum_tone_rewrite",
                "curriculum_tone_listen_mcq",
                "curriculum_tone_roleplay",
                name="task_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "active", "archived", name="task_status_enum"),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_index(op.f("ix_tasks_task_type"), "tasks", ["task_type"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "daily_plans",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_slug", sa.String(length=50), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.String(length=16), nullable=False),
        sa.Column(
            "plan_json",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "course_slug", "week", "day", name="uq_daily_plan_user_day"
        ),
    )
    op.create_index(
        "ix_daily_plan_lookup",
        "daily_plans",
        ["user_id", "course_slug", "week", "day"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_plans_course_slug"), "daily_plans", ["course_slug"], unique=False
    )
    op.create_index(
        op.f("ix_daily_plans_user_id"), "daily_plans", ["user_id"], unique=False
    )
    op.create_table(
        "oauth_accounts",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_user_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth_accounts_user_id"), "oauth_accounts", ["user_id"], unique=False
    )
    op.create_table(
        "purchases",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.String(length=50), nullable=False),
        sa.Column("plan_name", sa.String(length=120), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "currency", sa.String(length=3), server_default="INR", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=30), server_default="paid", nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_purchases_plan_id"), "purchases", ["plan_id"], unique=False
    )
    op.create_index(op.f("ix_purchases_status"), "purchases", ["status"], unique=False)
    op.create_index(op.f("ix_purchases_user_id"), "purchases", ["user_id"], unique=True)
    op.create_table(
        "skill_points",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("display_score", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_user_skill_points"),
    )
    op.create_index(
        op.f("ix_skill_points_skill_id"), "skill_points", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_skill_points_user_id"), "skill_points", ["user_id"], unique=False
    )
    op.create_table(
        "task_skills",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_skills_skill_id"), "task_skills", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_task_skills_task_id"), "task_skills", ["task_id"], unique=False
    )
    op.create_table(
        "user_enrollments",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("current_week", sa.Integer(), nullable=False),
        sa.Column("current_day_in_week", sa.Integer(), nullable=False),
        sa.Column("tasks_per_day", sa.Integer(), nullable=False),
        sa.Column("allow_reading", sa.Boolean(), nullable=False),
        sa.Column("allow_writing", sa.Boolean(), nullable=False),
        sa.Column("allow_listening", sa.Boolean(), nullable=False),
        sa.Column("allow_speaking", sa.Boolean(), nullable=False),
        sa.Column("current_day_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_completed_on", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "completed",
                "abandoned",
                name="enrollment_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tasks_per_day BETWEEN 2 AND 4",
            name="ck_user_enrollments_tasks_per_day_2_4",
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_enrollments_course_id"),
        "user_enrollments",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_enrollments_status"), "user_enrollments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_enrollments_user_id"),
        "user_enrollments",
        ["user_id"],
        unique=True,
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "self_assessed_level",
            sa.Enum(
                "BEGINNER", "INTERMEDIATE", "ADVANCED", name="self_assessed_level_enum"
            ),
            nullable=False,
        ),
        sa.Column("daily_time_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "content_exposure",
            sa.Enum("NONE", "LOW", "MEDIUM", "HIGH", name="content_exposure_enum"),
            nullable=False,
        ),
        sa.Column(
            "goal",
            sa.Enum("CASUAL", "PROFESSIONAL", "ACADEMIC", name="user_goal_enum"),
            nullable=False,
        ),
        sa.Column("interests", sa.String(length=500), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("phone_number", sa.String(length=40), nullable=True),
        sa.Column("country", sa.String(length=80), nullable=True),
        sa.Column("native_language", sa.String(length=80), nullable=True),
        sa.Column(
            "primary_goals", sa.String(length=500), server_default="", nullable=False
        ),
        sa.Column(
            "personalisation_context",
            sa.String(length=500),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "diagnosis_completed", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column(
            "daily_practice_reminder",
            sa.Boolean(),
            server_default="true",
            nullable=False,
        ),
        sa.Column(
            "streak_reminder", sa.Boolean(), server_default="true", nullable=False
        ),
        sa.Column(
            "weekly_progress_email",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column(
            "feature_announcements",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_skill_scores",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("is_estimated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_user_skill"),
    )
    op.create_index(
        op.f("ix_user_skill_scores_skill_id"),
        "user_skill_scores",
        ["skill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_skill_scores_user_id"),
        "user_skill_scores",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "enrollment_skill_history",
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_activity_type",
            sa.Enum(
                "reading",
                "writing",
                "speaking",
                "listening",
                "fill_in_blanks",
                "error_spotting",
                "sentence_transformation",
                "voice_conversion",
                "error_correction",
                "speak_with_tense",
                "curriculum_grammar_fill_blanks",
                "curriculum_grammar_open_text",
                "curriculum_grammar_listen_mcq",
                "curriculum_grammar_speak",
                "curriculum_vocab_mcq",
                "curriculum_vocab_open_text",
                "curriculum_vocab_listen_mcq",
                "curriculum_vocab_speak",
                "curriculum_pron_read_aloud",
                "curriculum_pron_phonetic_mcq",
                "curriculum_pron_listen_discriminate",
                "curriculum_pron_speak_drill",
                "curriculum_fluency_speed_read",
                "curriculum_fluency_timed_write",
                "curriculum_fluency_shadow",
                "curriculum_fluency_speak",
                "curriculum_expression_summarize",
                "curriculum_expression_essay",
                "curriculum_expression_listen_structure",
                "curriculum_expression_storyboard",
                "curriculum_comprehension_read_mcq",
                "curriculum_comprehension_write_answers",
                "curriculum_comprehension_listen_mcq",
                "curriculum_comprehension_retell",
                "curriculum_tone_read_mcq",
                "curriculum_tone_rewrite",
                "curriculum_tone_listen_mcq",
                "curriculum_tone_roleplay",
                name="task_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("times_practiced", sa.Integer(), nullable=False),
        sa.Column("last_practiced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["user_enrollments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("enrollment_id", "skill_id", name="uq_enrollment_skill"),
    )
    op.create_index(
        op.f("ix_enrollment_skill_history_enrollment_id"),
        "enrollment_skill_history",
        ["enrollment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrollment_skill_history_skill_id"),
        "enrollment_skill_history",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "user_tasks",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "skipped",
                name="user_task_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["user_enrollments.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_tasks_enrollment_id"),
        "user_tasks",
        ["enrollment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_tasks_status"), "user_tasks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_tasks_task_id"), "user_tasks", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_tasks_user_id"), "user_tasks", ["user_id"], unique=False
    )
    op.create_table(
        "learning_sessions",
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_id", sa.Integer(), nullable=False),
        sa.Column("user_task_id", sa.Integer(), nullable=True),
        sa.Column("phase", sa.String(length=32), nullable=False),
        sa.Column("topic", sa.String(length=200), nullable=False),
        sa.Column("skill_name", sa.String(length=50), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("user_level", sa.Integer(), nullable=False),
        sa.Column(
            "pre_generated_tasks",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "task_queue", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("current_task_index", sa.Integer(), nullable=False),
        sa.Column("messages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "user_submission", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("evaluation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("feedback", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("understanding_confirmed", sa.Boolean(), nullable=False),
        sa.Column("current_activity_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["enrollment_id"], ["user_enrollments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_task_id"], ["user_tasks.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_learning_sessions_enrollment_id"),
        "learning_sessions",
        ["enrollment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_sessions_session_id"),
        "learning_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_learning_sessions_user_id"),
        "learning_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_learning_sessions_user_task_id"),
        "learning_sessions",
        ["user_task_id"],
        unique=False,
    )
    op.create_table(
        "progress_logs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=3, scale=1), nullable=False),
        sa.Column("user_task_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_task_id"], ["user_tasks.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_progress_logs_skill_id"), "progress_logs", ["skill_id"], unique=False
    )
    op.create_index(
        op.f("ix_progress_logs_user_id"), "progress_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_progress_logs_user_task_id"),
        "progress_logs",
        ["user_task_id"],
        unique=False,
    )
    op.create_table(
        "skill_points_logs",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.Column("points_earned", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("user_task_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_task_id"], ["user_tasks.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_points_logs_skill_id"),
        "skill_points_logs",
        ["skill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_points_logs_user_id"),
        "skill_points_logs",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_skill_points_logs_user_task_id"),
        "skill_points_logs",
        ["user_task_id"],
        unique=False,
    )
    op.create_table(
        "user_responses",
        sa.Column("user_task_id", sa.Integer(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column(
            "embedding_status", sa.Text(), server_default="pending", nullable=False
        ),
        sa.Column("pinecone_vector_id", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_task_id"], ["user_tasks.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_responses_embedding_status"),
        "user_responses",
        ["embedding_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_responses_user_task_id"),
        "user_responses",
        ["user_task_id"],
        unique=True,
    )
    op.create_table(
        "evaluations",
        sa.Column("response_id", sa.Integer(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["response_id"], ["user_responses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluations_response_id"), "evaluations", ["response_id"], unique=True
    )
    op.create_table(
        "feedbacks",
        sa.Column("evaluation_id", sa.Integer(), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedbacks_evaluation_id"), "feedbacks", ["evaluation_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedbacks_evaluation_id"), table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_index(op.f("ix_evaluations_response_id"), table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_user_responses_user_task_id"), table_name="user_responses")
    op.drop_index(
        op.f("ix_user_responses_embedding_status"), table_name="user_responses"
    )
    op.drop_table("user_responses")
    op.drop_index(
        op.f("ix_skill_points_logs_user_task_id"), table_name="skill_points_logs"
    )
    op.drop_index(op.f("ix_skill_points_logs_user_id"), table_name="skill_points_logs")
    op.drop_index(op.f("ix_skill_points_logs_skill_id"), table_name="skill_points_logs")
    op.drop_table("skill_points_logs")
    op.drop_index(op.f("ix_progress_logs_user_task_id"), table_name="progress_logs")
    op.drop_index(op.f("ix_progress_logs_user_id"), table_name="progress_logs")
    op.drop_index(op.f("ix_progress_logs_skill_id"), table_name="progress_logs")
    op.drop_table("progress_logs")
    op.drop_index(
        op.f("ix_learning_sessions_user_task_id"), table_name="learning_sessions"
    )
    op.drop_index(op.f("ix_learning_sessions_user_id"), table_name="learning_sessions")
    op.drop_index(
        op.f("ix_learning_sessions_session_id"), table_name="learning_sessions"
    )
    op.drop_index(
        op.f("ix_learning_sessions_enrollment_id"), table_name="learning_sessions"
    )
    op.drop_table("learning_sessions")
    op.drop_index(op.f("ix_user_tasks_user_id"), table_name="user_tasks")
    op.drop_index(op.f("ix_user_tasks_task_id"), table_name="user_tasks")
    op.drop_index(op.f("ix_user_tasks_status"), table_name="user_tasks")
    op.drop_index(op.f("ix_user_tasks_enrollment_id"), table_name="user_tasks")
    op.drop_table("user_tasks")
    op.drop_index(
        op.f("ix_enrollment_skill_history_skill_id"),
        table_name="enrollment_skill_history",
    )
    op.drop_index(
        op.f("ix_enrollment_skill_history_enrollment_id"),
        table_name="enrollment_skill_history",
    )
    op.drop_table("enrollment_skill_history")
    op.drop_index(op.f("ix_user_skill_scores_user_id"), table_name="user_skill_scores")
    op.drop_index(op.f("ix_user_skill_scores_skill_id"), table_name="user_skill_scores")
    op.drop_table("user_skill_scores")
    op.drop_table("user_profiles")
    op.drop_index(op.f("ix_user_enrollments_user_id"), table_name="user_enrollments")
    op.drop_index(op.f("ix_user_enrollments_status"), table_name="user_enrollments")
    op.drop_index(op.f("ix_user_enrollments_course_id"), table_name="user_enrollments")
    op.drop_table("user_enrollments")
    op.drop_index(op.f("ix_task_skills_task_id"), table_name="task_skills")
    op.drop_index(op.f("ix_task_skills_skill_id"), table_name="task_skills")
    op.drop_table("task_skills")
    op.drop_index(op.f("ix_skill_points_user_id"), table_name="skill_points")
    op.drop_index(op.f("ix_skill_points_skill_id"), table_name="skill_points")
    op.drop_table("skill_points")
    op.drop_index(op.f("ix_purchases_user_id"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_status"), table_name="purchases")
    op.drop_index(op.f("ix_purchases_plan_id"), table_name="purchases")
    op.drop_table("purchases")
    op.drop_index(op.f("ix_oauth_accounts_user_id"), table_name="oauth_accounts")
    op.drop_table("oauth_accounts")
    op.drop_index(op.f("ix_daily_plans_user_id"), table_name="daily_plans")
    op.drop_index(op.f("ix_daily_plans_course_slug"), table_name="daily_plans")
    op.drop_index("ix_daily_plan_lookup", table_name="daily_plans")
    op.drop_table("daily_plans")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tasks_task_type"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_courses_status"), table_name="courses")
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
