"""add points-based scoring tables

Revision ID: d361e3b599b2
Revises: f81a4fd84a55
Create Date: 2026-05-09 12:09:53.328414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd361e3b599b2'
down_revision: Union[str, Sequence[str], None] = 'f81a4fd84a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_points',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('display_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skill_points')
    )
    op.create_index(op.f('ix_skill_points_skill_id'), 'skill_points', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_points_user_id'), 'skill_points', ['user_id'], unique=False)
    op.create_table('skill_points_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('user_task_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_task_id'], ['user_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_points_logs_skill_id'), 'skill_points_logs', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_points_logs_user_id'), 'skill_points_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_skill_points_logs_user_task_id'), 'skill_points_logs', ['user_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_points_logs_user_task_id'), table_name='skill_points_logs')
    op.drop_index(op.f('ix_skill_points_logs_user_id'), table_name='skill_points_logs')
    op.drop_index(op.f('ix_skill_points_logs_skill_id'), table_name='skill_points_logs')
    op.drop_table('skill_points_logs')
    op.drop_index(op.f('ix_skill_points_user_id'), table_name='skill_points')
    op.drop_index(op.f('ix_skill_points_skill_id'), table_name='skill_points')
    op.drop_table('skill_points')
    # ### end Alembic commands ###
