"""Task module models — Task, TaskSkill junction, and related enums."""

from datetime import datetime

from enum import Enum

from sqlalchemy import DateTime, Enum as SQLAlchemyEnum, ForeignKey, JSON, Numeric, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.modules.skills.models import Skill

from app.core.database import Base
from app.core.mixins import IDMixin, TimestampMixin


# Enums
class TaskType(str, Enum):
    """Task activity type — drives which UI component renders.

    The first four values (reading/writing/speaking/listening) are used by
    the rotation engine and seeded tasks.

    The remaining values are generated task types produced by the LLM
    Task Generator agent. They map 1-to-1 to template task_type strings
    so the frontend can detect them via isGeneratedTaskType().
    """
    # Seeded / rotation-engine activity types
    READING = "reading"
    WRITING = "writing"
    SPEAKING = "speaking"
    LISTENING = "listening"
    # LLM-generated task types (legacy grammar formats)
    FILL_IN_BLANKS = "fill_in_blanks"
    ERROR_SPOTTING = "error_spotting"
    SENTENCE_TRANSFORMATION = "sentence_transformation"
    VOICE_CONVERSION = "voice_conversion"
    ERROR_CORRECTION = "error_correction"
    SPEAK_WITH_TENSE = "speak_with_tense"
    # Curriculum-driven task types (28 templates — one per sub_skill × activity)
    CURRICULUM_GRAMMAR_FILL_BLANKS = "curriculum_grammar_fill_blanks"
    CURRICULUM_GRAMMAR_OPEN_TEXT = "curriculum_grammar_open_text"
    CURRICULUM_GRAMMAR_LISTEN_MCQ = "curriculum_grammar_listen_mcq"
    CURRICULUM_GRAMMAR_SPEAK = "curriculum_grammar_speak"
    CURRICULUM_VOCAB_MCQ = "curriculum_vocab_mcq"
    CURRICULUM_VOCAB_OPEN_TEXT = "curriculum_vocab_open_text"
    CURRICULUM_VOCAB_LISTEN_MCQ = "curriculum_vocab_listen_mcq"
    CURRICULUM_VOCAB_SPEAK = "curriculum_vocab_speak"
    CURRICULUM_PRON_READ_ALOUD = "curriculum_pron_read_aloud"
    CURRICULUM_PRON_PHONETIC_MCQ = "curriculum_pron_phonetic_mcq"
    CURRICULUM_PRON_LISTEN_DISCRIMINATE = "curriculum_pron_listen_discriminate"
    CURRICULUM_PRON_SPEAK_DRILL = "curriculum_pron_speak_drill"
    CURRICULUM_FLUENCY_SPEED_READ = "curriculum_fluency_speed_read"
    CURRICULUM_FLUENCY_TIMED_WRITE = "curriculum_fluency_timed_write"
    CURRICULUM_FLUENCY_SHADOW = "curriculum_fluency_shadow"
    CURRICULUM_FLUENCY_SPEAK = "curriculum_fluency_speak"
    CURRICULUM_EXPRESSION_SUMMARIZE = "curriculum_expression_summarize"
    CURRICULUM_EXPRESSION_ESSAY = "curriculum_expression_essay"
    CURRICULUM_EXPRESSION_LISTEN_STRUCTURE = "curriculum_expression_listen_structure"
    CURRICULUM_EXPRESSION_STORYBOARD = "curriculum_expression_storyboard"
    CURRICULUM_COMPREHENSION_READ_MCQ = "curriculum_comprehension_read_mcq"
    CURRICULUM_COMPREHENSION_WRITE_ANSWERS = "curriculum_comprehension_write_answers"
    CURRICULUM_COMPREHENSION_LISTEN_MCQ = "curriculum_comprehension_listen_mcq"
    CURRICULUM_COMPREHENSION_RETELL = "curriculum_comprehension_retell"
    CURRICULUM_TONE_READ_MCQ = "curriculum_tone_read_mcq"
    CURRICULUM_TONE_REWRITE = "curriculum_tone_rewrite"
    CURRICULUM_TONE_LISTEN_MCQ = "curriculum_tone_listen_mcq"
    CURRICULUM_TONE_ROLEPLAY = "curriculum_tone_roleplay"


class TaskStatus(str, Enum):
    """Lifecycle of a task template."""
    DRAFT = "draft"
    ACTIVE = "active"
    ARCHIVED = "archived"

class UserTaskStatus(str, Enum):
    """Lifecycle of an assigned task for a user."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    SKIPPED = "skipped"


# Task — the master template
class Task(Base, IDMixin, TimestampMixin):
    """
    A task template — generated by the Task Agent or hand-authored.

    `content` holds the full structured task (passage, questions, answers)
    as JSON. Schema varies by task_type; validated in service layer.
    """

    __tablename__ = "tasks"

    title: Mapped[str] = mapped_column(String(200), nullable=False)
    task_type: Mapped[TaskType] = mapped_column(
        SQLAlchemyEnum(
            TaskType,
            name="task_type_enum",
            values_callable=lambda e: [m.value for m in e],  # store lowercase values, not names
            create_type=False,  # type already exists in DB, managed by Alembic
        ),
        nullable=False,
        index=True,
    )
    difficulty: Mapped[int] = mapped_column(nullable=False, default=1)
    status: Mapped[TaskStatus] = mapped_column(
        SQLAlchemyEnum(
            TaskStatus,
            name="task_status_enum",
            values_callable=lambda e: [m.value for m in e],
            create_type=False,
        ),
        nullable=False, default=TaskStatus.ACTIVE, index=True,
    )
    # Full task body — passage, questions, answer keys. Shape depends on task_type.
    content: Mapped[dict] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=False,
    )

    # Relationships
    task_skills: Mapped[list["TaskSkill"]] = relationship(
        back_populates="task", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Task(id={self.id}, type={self.task_type.value}, title={self.title!r})>"


# TaskSkill — junction table for Task ↔ Skill (M:N) with weights
class TaskSkill(Base, IDMixin):
    """
    Junction table linking a task to the skills it targets.

    The `weight` column stores how much this task contributes to each skill's
    score (e.g., grammar=0.7, vocab=0.3 for a grammar-focused writing task).
    """

    __tablename__ = "task_skills"

    task_id: Mapped[int] = mapped_column(
        ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True
    )
    skill_id: Mapped[int] = mapped_column(
        ForeignKey("skills.id", ondelete="CASCADE"), nullable=False, index=True
    )
    weight: Mapped[float] = mapped_column(
        Numeric(3, 2), nullable=False, default=1.0
    )

    # Relationships
    task: Mapped["Task"] = relationship(back_populates="task_skills")
    skill: Mapped["Skill"] = relationship()  # one-way; reach via TaskSkill.skill

    def __repr__(self) -> str:
        return f"<TaskSkill(task_id={self.task_id}, skill_id={self.skill_id}, weight={self.weight})>"

class UserTask(Base, IDMixin, TimestampMixin):
    """
    A specific task assigned to a specific user.

    Tracks status, when assigned, when completed.
    The user's response (if any) hangs off this row in UserResponse.
    """

    __tablename__ = "user_tasks"

    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )
    task_id: Mapped[int] = mapped_column(
        ForeignKey("tasks.id", ondelete="CASCADE"), nullable=False, index=True
    )
    enrollment_id: Mapped[int | None] = mapped_column(
        ForeignKey("user_enrollments.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    status: Mapped[UserTaskStatus] = mapped_column(
        SQLAlchemyEnum(
            UserTaskStatus,
            name="user_task_status_enum",
            values_callable=lambda e: [m.value for m in e],
            create_type=False,
        ),
        nullable=False, default=UserTaskStatus.PENDING, index=True,
    )
    completed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationships 
    task: Mapped["Task"] = relationship()

    def __repr__(self) -> str:
        return (
            f"<UserTask(id={self.id}, user_id={self.user_id}, "
            f"task_id={self.task_id}, status={self.status.value})>"
        )
