"""Data access for Task templates and UserTask assignments"""

from sqlalchemy import select
from sqlalchemy.orm import Session, joinedload

from app.modules.tasks.models import (
    Task,
    TaskSkill,
    TaskStatus,
    TaskType,
    UserTask,
    UserTaskStatus,
)

class TaskRepository:
    """Read access to the Task template table.
    
    Tasks are seeded. (or generated by the Task Agent) and rarely deleted.
    No update/delete methods here yet - services don't need them.
    """

    def __init__(self, db: Session) -> None:
        self.db = db 

    def get_by_id(self, task_id: int) -> Task | None:
        """Single task by primary key. Returns None  if not found"""
        return self.db.get(Task, task_id)
    
    def list_by_skill(
        self,
        skill_id: int,
        *,
        status: TaskStatus = TaskStatus.ACTIVE
    ) -> list[Task]:
        """Return all tasks targeting the given skill.
        
        Joins through TaskSkill (the M:N junction). By default only returns
        ACTIVE tasks - drafts and archived are hidden from callers.

        `joinedload` eagerly fetched each task's skill links in the same
        query, so callers can iterate `task.task_skills`
        """
        return (
            self.db.query(Task)
            .join(TaskSkill, TaskSkill.task_id == Task.id)
            .filter(
                TaskSkill.skill_id == skill_id,
                Task.status == status,
            )
            .options(joinedload(Task.task_skills))
            .order_by(Task.difficulty, Task.id)
            .all()
        )
    
    def find_by_task_type(
        self,
        *,
        task_type: str,
        target_difficulty: int = 5,
    ) -> Task | None:
        """Find ONE seeded task matching a task_type string.

        Used only by the superuser dev panel as a fallback when LLM
        generation fails and we still want to show *something* for that
        task_type. Returns the ACTIVE task closest in difficulty.
        Returns None if no match exists in the seeded pool.
        """
        try:
            tt = TaskType(task_type)
        except ValueError:
            return None  # unknown task_type string

        from sqlalchemy import func
        return (
            self.db.query(Task)
            .filter(
                Task.status == TaskStatus.ACTIVE,
                Task.task_type == tt,
            )
            .order_by(
                func.abs(Task.difficulty - target_difficulty),
                Task.id,
            )
            .first()
        )

    def find_for_plan(
        self,
        *,
        skill_id: int,
        activity_type: TaskType,
        target_difficulty: int,
        exclude_completed_by_user_id: int | None = None,
    ) -> Task | None:
        """Find ONE task that matches a rotation engine's plan.

        Selection rules:
          - Task must be ACTIVE
          - Task must have task_type matching activity_type
          - Task must target the given skill (via TaskSkill junction)
          - If exclude_completed_by_user_id is given, skip tasks the user
            has already completed
          - Prefer tasks closest to target_difficulty
          - Tiebreak: lower id (oldest = most stable)

        Returns None if no task matches (caller should raise NoTaskAvailable).
        """
        query = (
            self.db.query(Task)
            .join(TaskSkill, TaskSkill.task_id == Task.id)
            .filter(
                Task.status == TaskStatus.ACTIVE,
                Task.task_type == activity_type,
                TaskSkill.skill_id == skill_id,
            )
            .options(joinedload(Task.task_skills))
        )

        if exclude_completed_by_user_id is not None:
            completed_subq = (
                self.db.query(UserTask.task_id)
                .filter(
                    UserTask.user_id == exclude_completed_by_user_id,
                    UserTask.status == UserTaskStatus.COMPLETED,
                )
                .subquery()
            )
            query = query.filter(Task.id.notin_(select(completed_subq)))

        # Order by closeness to target_difficulty using SQL abs()
        from sqlalchemy import func
        query = query.order_by(
            func.abs(Task.difficulty - target_difficulty),
            Task.id,
        )

        return query.first()
    
class UserTaskRepository:
    """All DB access for UserTask (a task assigned to a specific user)"""

    def __init__(self, db: Session) -> None:
        self.db = db 

    # Reads 
    def get_by_id(self, user_task_id: int) -> UserTask | None:
        """Single assignment by primary key"""
        return self.db.get(UserTask, user_task_id)
    
    def list_for_user(
        self,
        user_id: int,
        *,
        status: UserTaskStatus | None = None,
    ) -> list[UserTask]:
        """Return all task assignments for a user, newest first.
        
        if `status` is given, filter to only that status (e.g. only PENDING). 
        Eager-loads the related Task so callers can read `ut.task.title`
        without a second query per row.
        """
        query = (
            self.db.query(UserTask)
            .filter(UserTask.user_id == user_id)
            .options(joinedload(UserTask.task))
            .order_by(UserTask.created_at.desc())
        )
        if status is not None:
            query = query.filter(UserTask.status == status)
        
        return query.all()
    
    # Writes
    def assign(
        self,
        *,
        user_id: int,
        task_id: int,
        enrollment_id: int | None = None,
    ) -> UserTask:
        """Create a new assignment with default status (PENDING).

        `enrollment_id` is optional — set when the task came from a
        curriculum slot, None for ad-hoc/bonus tasks (future).
        """
        assignment = UserTask(
            user_id=user_id,
            task_id=task_id,
            enrollment_id=enrollment_id,
        )
        self.db.add(assignment)
        self.db.flush()
        return assignment
    
    def mark_completed(self, user_task: UserTask) -> UserTask:
        """Flip status to COMPLETED and stamp completed_at.
        
        Takes the ORM object directly (caller already has it from a read).
        Avoids a second SELECT just to fetch by id.
        """
        from datetime import datetime, timezone 
        
        user_task.status = UserTaskStatus.COMPLETED
        user_task.completed_at = datetime.now(timezone.utc)
        self.db.flush()
        return user_task 

    def find_active_for_enrollment_day(
        self,
        *,
        enrollment_id: int,
    ) -> list[UserTask]:
        """Return ALL open (PENDING or IN_PROGRESS) UserTasks for this
        enrollment. Used to check the current day's task bundle.

        Why this works: enrollment.current_week + current_day_in_week only
        advance when ALL tasks in the bundle are COMPLETED. So any
        non-completed UserTasks attached to this enrollment ARE the current
        day's tasks by definition.
        """
        return (
            self.db.query(UserTask)
            .filter(
                UserTask.enrollment_id == enrollment_id,
                UserTask.status.in_(
                    [UserTaskStatus.PENDING, UserTaskStatus.IN_PROGRESS]
                ),
            )
            .options(joinedload(UserTask.task))
            .order_by(UserTask.created_at.asc())
            .all()
        )

